"""
Django settings for DrSl project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
from cryptography.fernet import Fernet

# =========================================================
# БАЗОВЫЕ ПУТИ
# =========================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
# БЕЗОПАСНОСТЬ
# =========================================================
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-*t7m4symt6n9bbmcx$uksz$6nm6spm-qrv=^my&w(vl#ed0^l3"
)
DEBUG = True
ALLOWED_HOSTS = []

# =========================================================
# УСТАНОВЛЕННЫЕ ПРИЛОЖЕНИЯ
# =========================================================
INSTALLED_APPS = [
    'jazzmin',  # Должен идти первым
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Пользовательские приложения
    'vault',
    'groups',
    'students',
    'classrooms',
    'teachers.apps.TeachersConfig',
    'reference',
    'masters',
    'reports',
    'DrSl',
]

# =========================================================
# MIDDLEWARE
# =========================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =========================================================
# URL / WSGI
# =========================================================
ROOT_URLCONF = 'DrSl.urls'
WSGI_APPLICATION = 'DrSl.wsgi.application'

# =========================================================
# ШАБЛОНЫ
# =========================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# =========================================================
# БАЗА ДАННЫХ
# =========================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# =========================================================
# ВАЛИДАЦИЯ ПАРОЛЕЙ
# =========================================================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =========================================================
# ШИФРОВАНИЕ ДАННЫХ VAULT
# =========================================================
VAULT_ENCRYPTION_KEY = os.environ.get("VAULT_ENCRYPTION_KEY", Fernet.generate_key().decode())

# =========================================================
# ЛОКАЛИЗАЦИЯ И ФОРМАТЫ
# =========================================================
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = False  # Отключаем timezone для простоты работы с датами

# Форматы дат для всего проекта
DATE_INPUT_FORMATS = ['%d.%m.%Y', '%d/%m/%Y']
DATE_FORMAT = 'd.m.Y'
SHORT_DATE_FORMAT = 'd.m.Y'

# =========================================================
# СТАТИЧЕСКИЕ ФАЙЛЫ
# =========================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Для collectstatic

# =========================================================
# АВТОРИЗАЦИЯ
# =========================================================
LOGIN_URL = 'home'
LOGIN_REDIRECT_URL = 'vault:dashboard'
LOGOUT_REDIRECT_URL = 'home'

# =========================================================
# НАСТРОЙКИ АДМИНКИ
# =========================================================
ADMIN_SITE_HEADER = "🔐 Автошкола — Администрирование"
ADMIN_SITE_TITLE = "Панель управления"
ADMIN_INDEX_TITLE = "Добро пожаловать!"

# =========================================================
# НАСТРОЙКИ JAZZMIN (ЧИСТЫЙ ВАРИАНТ)
# =========================================================

JAZZMIN_SETTINGS = {
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "classrooms.classroom": "vertical",
        "groups.group": "vertical_tabs",
        "students.student": "vertical_tabs",
        "teachers.teacher": "vertical_tabs",
    },
    "copyright": "Автошкола © 2026",
    "default_icon_children": "fas fa-circle",
    "default_icon_parents": "fas fa-chevron-circle-right",

    "icons": {
        "auth": "fas fa-users-cog",
        "classrooms": "fas fa-door-open",
        "groups": "fas fa-layer-group",
        "masters.master": "fas fa-user-cog",
        "reference": "fas fa-book-open",
        "reference.groupcategory": "fas fa-folder-open",
        "students": "fas fa-user-graduate",
        "teachers": "fas fa-chalkboard-teacher",
        "vault": "fas fa-key",
    },

    "navigation_expanded": True,

    # ✅ Просто порядок приложений — Категории и Аудитории идут подряд
    "order_with_respect_to": [
        "vault",
        "groups",
        "students",
        "teachers",
        "masters",
        "reference",  # 📂 Категории
        "classrooms",  # 🚪 Аудитории (сразу после)
        "auth",
    ],

    # ❌ УБРАНО: custom_links и hide_apps — они вызывали ошибку
    # ❌ УБРАНО: "custom_links": [...], "hide_apps": [...]

    "related_modal_active": True,
    "search_model": ["auth.User", "vault.VaultEntry"],
    "show_sidebar": True,
    "show_ui_builder": False,
    "site_brand": "🚗 Автошкола",
    "site_header": "🔐 Автошкола",
    "site_title": "Автошкола Админ",
    "site_url": "/vault/",
    "user_avatar": None,
    "welcome_sign": "Добро пожаловать в панель управления",
}
# =========================================================
# ЛОГИРОВАНИЕ
# =========================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}# Игнорировать 404 для favicon
import logging
logging.getLogger('django.request').addFilter(
    lambda r: not r.getMessage().endswith('favicon.ico')
)
