# Generated by Django 6.0.4 on 2026-09-14 12:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('masters', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(help_text='Формат: +375 (29) 123-45-67', max_length=25, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) 123-45-67', regex='^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, verbose_name='Место рождения')),
                ('place_of_residence', models.CharField(blank=True, max_length=255, verbose_name='Место проживания')),
                ('place_of_registration', models.CharField(blank=True, max_length=255, verbose_name='Место регистрации')),
                ('work_study_place', models.CharField(blank=True, max_length=255, verbose_name='Место работы/учёбы')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('gearbox_type', models.CharField(blank=True, choices=[('', '— Не выбрано —'), ('manual', ' Механическая'), ('auto', '🤖 Автоматическая')], default='', help_text='Выберите тип коробки передач для обучения', max_length=50, verbose_name='Тип КПП')),
                ('enrolled_date', models.DateField(blank=True, null=True, verbose_name='Дата зачисления')),
                ('graduated_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('driving_hours_required', models.IntegerField(default=0, help_text='Устанавливается при добавлении группы в генплан', verbose_name='Положено часов вождения')),
                ('driving_hours_completed', models.IntegerField(default=0, help_text='Заполняется из путевых листов', verbose_name='Выкатано часов')),
                ('activity_log', models.JSONField(blank=True, default=list, help_text='Общий журнал: переводы, зачёты, изменения статусов (сортируется по дате)', verbose_name='Журнал активности')),
                ('transferred_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего перевода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group', verbose_name='Группа')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.masterpouts', verbose_name='Мастер вождения')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Учащийся',
                'verbose_name_plural': '🎓 Учащиеся',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('dismissed', '❌ Отчислен'), ('transferred', ' Переведён'), ('contract_extended', '📄 Продление договора'), ('notified', '🔔 Уведомление'), ('suspended', '⏸️ Приостановка'), ('refused', '🚫 Отказ от обучения'), ('activated', '✅ Активирован'), ('other', '📝 Другое')], max_length=30, verbose_name='Тип события')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='Дата события')),
                ('order_number', models.CharField(blank=True, help_text='Заполняется для отчислений', max_length=50, verbose_name='№ приказа')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация о событии', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='students.student', verbose_name='Учащийся')),
            ],
            options={
                'verbose_name': 'Запись в истории',
                'verbose_name_plural': '📜 История учащихся',
                'ordering': ['-created_at', '-event_date'],
            },
        ),
    ]
