# Generated by Django 6.0.4 on 2026-04-29 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Завершена')], default='active', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('theory_status', models.CharField(choices=[('not_started', '⚪ Не начато'), ('in_progress', '🟡 В процессе'), ('passed', '🟢 Сдал'), ('failed', '🔴 Не сдал')], default='not_started', max_length=20, verbose_name='Теория')),
                ('driving_status', models.CharField(choices=[('not_started', '⚪ Не начато'), ('in_progress', '🟡 В процессе'), ('passed', '🟢 Сдал'), ('failed', '🔴 Не сдал')], default='not_started', max_length=20, verbose_name='Вождение')),
                ('enrolled_date', models.DateField(auto_now_add=True, verbose_name='Дата зачисления')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.group', verbose_name='Группа')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Инструктор')),
            ],
            options={
                'verbose_name': 'Учащийся',
                'verbose_name_plural': 'Учащиеся',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
