# Generated by Django 6.0.4 on 2026-04-30 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='student',
            name='work_study_place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место работы/учёбы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +375 (29) 123-45-67', max_length=18, validators=[django.core.validators.RegexValidator(message='Введите номер в формате: +375 (29) 123-45-67', regex='^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
