# Generated by Django 6.0.4 on 2026-04-30 13:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_birth_date_student_position_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Группа', 'verbose_name_plural': '👥 Группы'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
        migrations.AddField(
            model_name='group',
            name='category',
            field=models.CharField(default=None, max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Ровно 2 заглавные буквы')], verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='classroom',
            field=models.CharField(default=None, max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{4}$', 'Ровно 4 символа')], verbose_name='Аудитория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='по'),
        ),
        migrations.AddField(
            model_name='group',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Действие договора с'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='group_number',
            field=models.CharField(default=None, max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'Ровно 6 заглавных букв или цифр')], verbose_name='№ группы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_exceptions',
            field=models.JSONField(blank=True, default=list, help_text='Даты в формате ГГГГ-ММ-ДД через запятую', verbose_name='Исключения из расписания'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_type',
            field=models.CharField(choices=[('odd', '📅 Нечётные дни (пн-пт)'), ('even', '📅 Чётные дни (пн-пт)'), ('weekend', '📅 Выходные (сб-вс)')], default='odd', max_length=10, verbose_name='Тип расписания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'teachers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_session',
            field=models.CharField(choices=[('morning', '🌅 Утренняя'), ('evening', '🌆 Вечерняя')], default=django.utils.timezone.now, max_length=10, verbose_name='Смена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', '🟢 Активная'), ('archived', '⚪ Архив')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, help_text='Формат: +375 (29) 123-45-67', max_length=25, validators=[django.core.validators.RegexValidator(message='Введите номер в формате: +375 (29) 123-45-67', regex='^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
