# Generated by Django 6.0.4 on 2026-05-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0003_alter_group_options_remove_group_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group', verbose_name='Группа'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
