# Generated by Django 6.0.4 on 2026-05-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_registration',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место прописки'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проживания'),
        ),
    ]
