# Generated by Django 6.0.4 on 2026-05-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('students', '0006_student_place_of_birth_student_place_of_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instructor',
        ),
        migrations.AddField(
            model_name='student',
            name='master',
            field=models.ForeignKey(blank=True, help_text='Мастер производственного обучения (вождение)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.master', verbose_name='Мастер'),
        ),
    ]
