# Generated by Django 6.0.4 on 2026-05-13 11:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('students', '0007_remove_student_instructor_student_master'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Учащийся', 'verbose_name_plural': '🎓 Учащиеся'},
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gai_exam_date',
            field=models.DateField(blank=True, help_text='Вводится вручную', null=True, verbose_name='Дата экзамена в ГАИ'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated_date',
            field=models.DateField(blank=True, help_text='Вводится вручную', null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AddField(
            model_name='student',
            name='transfer_log',
            field=models.JSONField(blank=True, default=list, editable=False, help_text='Заполняется автоматически при смене группы', verbose_name='История переводов'),
        ),
        migrations.AddField(
            model_name='student',
            name='transferred_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Дата последнего перевода'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrolled_date',
            field=models.DateField(blank=True, help_text='Вводится вручную', null=True, verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.master', verbose_name='Мастер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$', 'Формат: +375 (29) 123-45-67')], verbose_name='Телефон'),
        ),
    ]
