# Generated by Django 6.0.4 on 2026-05-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_options_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gai_exam_passed',
            field=models.BooleanField(default=False, verbose_name='Сдал экзамен в ГАИ'),
        ),
        migrations.AddField(
            model_name='student',
            name='gai_exam_retake_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата пересдачи (ГАИ)'),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата внутреннего экзамена'),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_exam_passed',
            field=models.BooleanField(default=False, verbose_name='Сдал внутренний экзамен'),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_exam_retake_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата пересдачи (внутр.)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gai_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата экзамена в ГАИ'),
        ),
    ]
