# Generated by Django 6.0.4 on 2026-05-14 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_gai_exam_passed_student_gai_exam_retake_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gai_exam_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gai_exam_passed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gai_exam_retake_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='graduated_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_exam_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_exam_passed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_exam_retake_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='master',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_registration',
        ),
        migrations.RemoveField(
            model_name='student',
            name='place_of_residence',
        ),
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.RemoveField(
            model_name='student',
            name='work_study_place',
        ),
        migrations.AlterField(
            model_name='student',
            name='driving_status',
            field=models.CharField(choices=[('not_started', '⚪ Не начато'), ('in_progress', '🟡 В процессе'), ('passed', '🟢 Сдано')], default='not_started', max_length=20, verbose_name='Вождение'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(help_text='Формат: +375 (29) 123-45-67', max_length=25, validators=[django.core.validators.RegexValidator('^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$', 'Формат: +375 (29) 123-45-67')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='student',
            name='theory_status',
            field=models.CharField(choices=[('not_started', '⚪ Не начато'), ('in_progress', '🟡 В процессе'), ('passed', '🟢 Сдано')], default='not_started', max_length=20, verbose_name='Теория'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_log',
            field=models.JSONField(blank=True, default=list, verbose_name='Журнал переводов'),
        ),
        migrations.AlterField(
            model_name='student',
            name='transferred_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего перевода'),
        ),
    ]
