# Generated by Django 6.0.4 on 2026-05-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_daily_schedule'),
        ('masters', '0001_initial'),
        ('students', '0010_remove_student_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='driving_status',
        ),
        migrations.RemoveField(
            model_name='student',
            name='theory_status',
        ),
        migrations.AddField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='enrolled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата зачисления'),
        ),
        migrations.AddField(
            model_name='student',
            name='gai_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата экзамена ГАИ'),
        ),
        migrations.AddField(
            model_name='student',
            name='gai_exam_passed',
            field=models.BooleanField(default=False, verbose_name='Сдал ГАИ'),
        ),
        migrations.AddField(
            model_name='student',
            name='gai_exam_retake_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата пересдачи (ГАИ)'),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выпуска'),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата внутреннего экзамена'),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_exam_passed',
            field=models.BooleanField(default=False, verbose_name='Сдал внутренний'),
        ),
        migrations.AddField(
            model_name='student',
            name='internal_exam_retake_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата пересдачи (внутр.)'),
        ),
        migrations.AddField(
            model_name='student',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.master', verbose_name='Мастер вождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место рождения'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_registration',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место регистрации'),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место проживания'),
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, max_length=100, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='student',
            name='work_study_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы/учёбы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='groups.group', verbose_name='Группа'),
        ),
    ]
