# Generated by Django 6.0.4 on 2026-05-18 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_remove_student_driving_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('dismissed', '❌ Отчислен'), ('transferred', '🔄 Переведён'), ('contract_extended', '📄 Продление договора'), ('notified', '🔔 Уведомление'), ('suspended', '⏸️ Приостановка'), ('refused', '🚫 Отказ от обучения'), ('other', '📝 Другое')], max_length=30, verbose_name='Тип события')),
                ('event_date', models.DateField(auto_now_add=True, verbose_name='Дата события')),
                ('order_number', models.CharField(blank=True, help_text='Заполняется для отчислений', max_length=50, verbose_name='№ приказа')),
                ('order_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('comment', models.TextField(blank=True, help_text='Доп. информация о событии', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='students.student', verbose_name='Учащийся')),
            ],
            options={
                'verbose_name': 'Запись в истории',
                'verbose_name_plural': '📜 История учащихся',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
