# Generated by Django 6.0.4 on 2026-05-18 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(help_text='Формат: +375 (29) 123-45-67', max_length=25, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) 123-45-67', regex='^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='comment',
            field=models.TextField(blank=True, help_text='Дополнительная информация о событии', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата события'),
        ),
    ]
