# Generated by Django 6.0.4 on 2026-05-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_phone_alter_studenthistory_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gai_exam_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gai_exam_passed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gai_exam_retake_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_exam_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_exam_passed',
        ),
        migrations.RemoveField(
            model_name='student',
            name='internal_exam_retake_date',
        ),
    ]
