# Generated by Django 6.0.4 on 2026-05-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_student_gai_exam_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='event_type',
            field=models.CharField(choices=[('dismissed', '❌ Отчислен'), ('transferred', '🔄 Переведён'), ('contract_extended', '📄 Продление договора'), ('notified', '🔔 Уведомление'), ('suspended', '⏸️ Приостановка'), ('refused', '🚫 Отказ от обучения'), ('activated', '✅ Активирован'), ('other', '📝 Другое')], max_length=30, verbose_name='Тип события'),
        ),
    ]
