# Generated by Django 6.0.4 on 2026-05-21 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studenthistory_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenthistory',
            options={'ordering': ['-created_at', '-event_date'], 'verbose_name': 'Запись в истории', 'verbose_name_plural': '📜 История учащихся'},
        ),
    ]
