# Generated by Django 6.0.4 on 2026-05-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_alter_studenthistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='transfer_log',
        ),
        migrations.AddField(
            model_name='student',
            name='activity_log',
            field=models.JSONField(blank=True, default=list, help_text='Общий журнал: переводы, зачёты, изменения статусов (сортируется по дате)', verbose_name='Журнал активности'),
        ),
    ]
