# Generated by Django 6.0.4 on 2026-05-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_remove_student_transfer_log_student_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gearbox_type',
            field=models.CharField(blank=True, choices=[('', '— Не выбрано —'), ('manual', '🔧 Механическая'), ('auto', '🤖 Автоматическая')], default='', help_text='Выберите тип коробки передач для обучения', max_length=10, verbose_name='Тип КПП'),
        ),
    ]
