# Generated by Django 6.0.4 on 2026-09-14 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('passport_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-ZА-Я]{2} \\d{7}$', 'Формат: 2 заглавные буквы, пробел, 7 цифр (например: HB 1234567)')], verbose_name='№ паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('license_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z]{3} \\d{6}$', 'Формат: 3 заглавные латинские буквы, пробел, 6 цифр (например: AAA 123456)')], verbose_name='№ водительского удостоверения')),
                ('license_category', models.JSONField(blank=True, default=list, help_text='Выберите одну или несколько категорий', verbose_name='Категории ВУ')),
                ('license_expiry', models.DateField(verbose_name='Срок действия ВУ')),
                ('medical_cert_number', models.CharField(blank=True, max_length=30, verbose_name='№ медицинской справки')),
                ('medical_cert_expiry', models.DateField(blank=True, null=True, verbose_name='Срок действия мед. справки')),
                ('qualification_cert_number', models.CharField(blank=True, max_length=50, verbose_name='№ свидетельства о повышении квалификации')),
                ('qualification_cert_expiry', models.DateField(blank=True, null=True, verbose_name='Срок действия свидетельства')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$', 'Формат: +375 (XX) XXX-XX-XX')], verbose_name='Номер телефона')),
                ('fuel_card_number', models.CharField(help_text='Ровно 9 цифр', max_length=9, validators=[django.core.validators.MinLengthValidator(9, 'Ровно 9 знаков'), django.core.validators.MaxLengthValidator(9, 'Ровно 9 знаков'), django.core.validators.RegexValidator('^\\d{9}$', 'Только 9 цифр')], verbose_name='№ топливной карты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='cars.car', verbose_name='Закреплённый автомобиль')),
            ],
            options={
                'verbose_name': 'Мастер ПОУТС',
                'verbose_name_plural': '🚗 Мастера ПОУТС',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
