# Generated by Django 6.0.4 on 2026-05-13 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0003_alter_groupcategory_options_alter_groupcategory_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес проживания')),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator('^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$', 'Формат: +375 (29) 123-45-67')], verbose_name='Номер телефона')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='Номер водительского удостоверения')),
                ('license_expiry', models.DateField(blank=True, null=True, verbose_name='Срок действия ВУ')),
                ('medical_expiry', models.DateField(blank=True, null=True, verbose_name='Срок действия мед. справки')),
                ('work_time_start', models.TimeField(blank=True, null=True, verbose_name='Начало работы')),
                ('work_time_end', models.TimeField(blank=True, null=True, verbose_name='Окончание работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('license_categories', models.ManyToManyField(blank=True, related_name='masters_with_license', to='reference.groupcategory', verbose_name='Категории прав')),
                ('teaching_categories', models.ManyToManyField(blank=True, related_name='masters_teaching', to='reference.groupcategory', verbose_name='Категории обучает')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': '🚗 Мастера',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
