# Generated by Django 6.0.4 on 2026-05-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='№ аудитории')),
                ('location', models.CharField(max_length=250, verbose_name='Класс / Адрес')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ договора')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Действует по')),
                ('san_certificate_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ свидетельства (СЭС)')),
                ('san_certificate_valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='Количество учащихся')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': '🏫 Аудитории',
                'ordering': ['number'],
            },
        ),
    ]
