# Generated by Django 6.0.4 on 2026-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_number', models.CharField(max_length=10, unique=True, verbose_name='№ аудитории')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('capacity', models.PositiveSmallIntegerField(default=20, verbose_name='Количество учащихся')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='№ договора')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Действует с')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='по')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договора')),
                ('san_certificate_valid_until', models.DateField(blank=True, null=True, verbose_name='СЭС действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': '🏫 Аудитории',
                'ordering': ['classroom_number'],
            },
        ),
    ]
