# Generated by Django 6.0.4 on 2026-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['classroom_number'], 'verbose_name': 'Аудитория', 'verbose_name_plural': '🏫 Аудитории'},
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='number',
            new_name='classroom_number',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='location',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='san_certificate_number',
        ),
        migrations.AddField(
            model_name='classroom',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Файл договора'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Количество учащихся'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='san_certificate_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='СЭС действует до'),
        ),
    ]
