# Generated by Django 6.0.4 on 2026-05-06 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Введите ровно 2 заглавные буквы')], verbose_name='Код (2 знака)')),
                ('description', models.TextField(help_text='Будет отображаться при наведении на категорию', verbose_name='Описание / Подсказка')),
            ],
            options={
                'verbose_name': 'Категория группы',
                'verbose_name_plural': '📂 Категории групп (Справочник)',
                'ordering': ['code'],
            },
        ),
    ]
