# Generated by Django 6.0.4 on 2026-09-14 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Зачёт',
                'verbose_name_plural': '✅ Зачёты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,2}$', '1-2 заглавные буквы или цифры')], verbose_name='Код (1-2 знака)')),
                ('description', models.TextField(help_text='Отображается в таблице', verbose_name='Описание')),
                ('hint', models.TextField(blank=True, help_text='Всплывает при наведении', verbose_name='Подсказка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': ' Категории',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('short_name', models.CharField(help_text='Используется в базе данных: pdd, ua, bd...', max_length=20, unique=True, verbose_name='Код (латиницей)')),
                ('short_name_display', models.CharField(blank=True, default='', help_text='Отображается в заголовках и таблицах: ПДД, УА, БД...', max_length=50, verbose_name='Краткое обозначение (кириллицей)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='subjects', to='reference.groupcategory', verbose_name='Категории транспортных средств')),
            ],
            options={
                'verbose_name': 'Учебный предмет',
                'verbose_name_plural': '📚 Учебные предметы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Количество часов')),
                ('topic_number', models.PositiveIntegerField(verbose_name='Тема №')),
                ('content', models.TextField(verbose_name='Содержание темы')),
                ('is_pz', models.BooleanField(default=False, verbose_name='Практическое занятие (ПЗ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topics', to='reference.subjectdictionary', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Тема занятия',
                'verbose_name_plural': '📚 Темы занятий',
            },
        ),
        migrations.CreateModel(
            name='SubjectSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='subject_sets', to='reference.groupcategory', verbose_name='Категории транспортных средств')),
                ('subjects', models.ManyToManyField(blank=True, related_name='subject_sets', to='reference.subjectdictionary', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Набор предметов',
                'verbose_name_plural': '📦 Наборы предметов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('total_hours', models.DecimalField(decimal_places=1, help_text='Например: 170 для категории B', max_digits=5, verbose_name='Общее количество часов')),
                ('plan_graphic_title', models.CharField(blank=True, default='План-график выполнения единой программы', help_text='Текст заголовка, который будет подставлен в Excel-файл план-графика', max_length=300, verbose_name='План-график выполнения единой программы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='training_programs', to='reference.groupcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': '📋 Программы обучения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включён')),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Часов по предмету')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='reference.subjectdictionary')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='reference.trainingprogram')),
            ],
            options={
                'ordering': ['subject__short_name'],
                'unique_together': {('program', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ProgramTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, help_text='Количество часов на эту тему', max_digits=4, verbose_name='Часов')),
                ('program_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='reference.programsubject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_topics', to='reference.lessontopic')),
            ],
            options={
                'ordering': ['topic__topic_number'],
                'unique_together': {('program_subject', 'topic')},
            },
        ),
    ]
