# Generated by Django 6.0.4 on 2026-05-06 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcategory',
            name='hint',
            field=models.TextField(blank=True, help_text='Всплывает при наведении (необязательно)', verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='code',
            field=models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,2}$', '1-2 заглавные буквы или цифры')], verbose_name='Код (1-2 знака)'),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='description',
            field=models.TextField(help_text='Отображается в таблице', verbose_name='Описание'),
        ),
    ]
