# Generated by Django 6.0.4 on 2026-05-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_groupcategory_hint_alter_groupcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'ordering': ['code'], 'verbose_name': 'Категория', 'verbose_name_plural': '📁 Категории'},
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='hint',
            field=models.TextField(blank=True, help_text='Всплывает при наведении', verbose_name='Подсказка'),
        ),
    ]
