# Generated by Django 6.0.4 on 2026-05-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_alter_groupcategory_options_alter_groupcategory_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Зачёт',
                'verbose_name_plural': '📝 Зачёты',
                'ordering': ['number'],
            },
        ),
    ]
