# Generated by Django 6.0.4 on 2026-05-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['number'], 'verbose_name': 'Зачёт', 'verbose_name_plural': '✅ Зачёты'},
        ),
    ]
