# Generated by Django 6.0.4 on 2026-06-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_alter_credit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pdd', '📕 Правила дорожного движения (ПДД)'), ('outs_bd', '📗 Основы управления ТС и безопасность (ОУТС и БД)'), ('podd', '📘 Правовые основы дорожного движения (ПОДД)'), ('mp', '📙 Медицинская помощь пострадавшим в ДТП (МП)')], max_length=20, verbose_name='Справочник')),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Количество часов')),
                ('topic_number', models.PositiveIntegerField(verbose_name='Тема №')),
                ('content', models.TextField(verbose_name='Содержание темы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тема занятия',
                'verbose_name_plural': '📚 Темы занятий',
                'ordering': ['category', 'topic_number'],
                'unique_together': {('category', 'topic_number')},
            },
        ),
    ]
