# Generated by Django 6.0.4 on 2026-06-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_lessontopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontopic',
            name='hours',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Количество часов'),
        ),
    ]
