# Generated by Django 6.0.4 on 2026-06-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0007_alter_lessontopic_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessontopic',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='category',
            field=models.CharField(choices=[('pdd', 'Правила дорожного движения (ПДД)'), ('outs_bd', 'Основы управления ТС и безопасность (ОУТС и БД)'), ('podd', 'Правовые основы дорожного движения (ПОДД)'), ('mp', 'Медицинская помощь пострадавшим в ДТП (МП)'), ('ua', 'Устройство автомобиля (УА)')], max_length=20, verbose_name='Справочник'),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Количество часов'),
        ),
    ]
