# Generated by Django 6.0.4 on 2026-06-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_alter_lessontopic_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontopic',
            name='category',
            field=models.CharField(choices=[('pdd', 'Правила дорожного движения (ПДД)'), ('outs_bd', 'Основы управления транспортным средством и безопасность движения (ОУТС и БД)'), ('podd', 'Правовые основы дорожного движения (ПОДД)'), ('mp', 'Первая помощь пострадавшим при дорожно-транспортных происшествиях (МП)'), ('ua', 'Устройство и техническое обслуживание автомобилей категории «B» (УА)')], max_length=20, verbose_name='Справочник'),
        ),
    ]
