# Generated by Django 6.0.4 on 2026-07-01 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_alter_lessontopic_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название предмета')),
                ('short_name', models.CharField(help_text='Например: pdd, ua, bd, podd, med, exam', max_length=20, unique=True, verbose_name='Краткое обозначение (латиницей)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учебный предмет',
                'verbose_name_plural': '📚 Учебные предметы',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='lessontopic',
            options={'ordering': ['subject', 'topic_number'], 'verbose_name': 'Тема занятия', 'verbose_name_plural': '📚 Темы занятий'},
        ),
        migrations.RemoveField(
            model_name='lessontopic',
            name='category',
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='reference.subjectdictionary', verbose_name='Предмет'),
        ),
    ]
