# Generated by Django 6.0.4 on 2026-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_subjectdictionary_alter_lessontopic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdictionary',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории, для которых предназначен предмет', related_name='subjects', to='reference.groupcategory', verbose_name='Категории транспортных средств'),
        ),
    ]
