# Generated by Django 6.0.4 on 2026-07-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_subjectdictionary_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='subject_sets', to='reference.groupcategory', verbose_name='Категории транспортных средств')),
                ('subjects', models.ManyToManyField(blank=True, related_name='subject_sets', to='reference.subjectdictionary', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Набор предметов',
                'verbose_name_plural': '📦 Наборы предметов',
                'ordering': ['name'],
            },
        ),
    ]
