# Generated by Django 6.0.4 on 2026-07-02 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0012_subjectset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectset',
            options={'ordering': ['name'], 'verbose_name': 'Набор предметов', 'verbose_name_plural': ' Наборы предметов'},
        ),
    ]
