# Generated by Django 6.0.4 on 2026-07-02 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0013_alter_subjectset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'ordering': ['code'], 'verbose_name': 'Категория', 'verbose_name_plural': ' Категории'},
        ),
        migrations.AlterModelOptions(
            name='lessontopic',
            options={'ordering': ['subject', 'topic_number'], 'verbose_name': 'Тема занятия', 'verbose_name_plural': ' Темы занятий'},
        ),
        migrations.AlterModelOptions(
            name='subjectset',
            options={'ordering': ['name'], 'verbose_name': 'Набор предметов', 'verbose_name_plural': '📦 Наборы предметов'},
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название программы')),
                ('total_hours', models.DecimalField(decimal_places=1, help_text='Например: 170 для категории B', max_digits=5, verbose_name='Общее количество часов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='training_programs', to='reference.groupcategory', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Программа обучения',
                'verbose_name_plural': '📋 Программы обучения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включён')),
                ('hours', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='Часов по предмету')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='reference.subjectdictionary')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='reference.trainingprogram')),
            ],
            options={
                'ordering': ['subject__short_name'],
                'unique_together': {('program', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='ProgramTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.DecimalField(decimal_places=1, help_text='Количество часов на эту тему', max_digits=4, verbose_name='Часов')),
                ('program_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='reference.programsubject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_topics', to='reference.lessontopic')),
            ],
            options={
                'ordering': ['topic__topic_number'],
                'unique_together': {('program_subject', 'topic')},
            },
        ),
    ]
