# Generated by Django 6.0.4 on 2026-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0014_alter_groupcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectdictionary',
            name='short_name_display',
            field=models.CharField(blank=True, default='', help_text='Отображается в заголовках и таблицах: ПДД, УА, БД...', max_length=50, verbose_name='Краткое обозначение (кириллицей)'),
        ),
        migrations.AlterField(
            model_name='subjectdictionary',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='reference.groupcategory', verbose_name='Категории транспортных средств'),
        ),
        migrations.AlterField(
            model_name='subjectdictionary',
            name='short_name',
            field=models.CharField(help_text='Используется в базе данных: pdd, ua, bd...', max_length=20, unique=True, verbose_name='Код (латиницей)'),
        ),
    ]
