# Generated by Django 6.0.4 on 2026-07-15 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0015_subjectdictionary_short_name_display_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'ordering': ['code'], 'verbose_name': 'Категория', 'verbose_name_plural': '📂 Категории'},
        ),
        migrations.AlterModelOptions(
            name='lessontopic',
            options={'ordering': ['subject', 'topic_number', 'is_pz'], 'verbose_name': 'Тема занятия', 'verbose_name_plural': ' Темы занятий'},
        ),
        migrations.AlterModelOptions(
            name='programtopic',
            options={'ordering': ['topic__topic_number', 'topic__is_pz']},
        ),
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ['name'], 'verbose_name': 'Программа обучения', 'verbose_name_plural': ' Программы обучения'},
        ),
        migrations.AddField(
            model_name='lessontopic',
            name='is_pz',
            field=models.BooleanField(default=False, verbose_name='Практическое занятие (ПЗ)'),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='hours',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Базовое количество часов (может переопределяться в программе)', max_digits=4, verbose_name='Количество часов (справочно)'),
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_topics', to='reference.subjectdictionary', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='programsubject',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Включён в программу'),
        ),
        migrations.AlterField(
            model_name='programsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_subjects', to='reference.subjectdictionary'),
        ),
        migrations.AlterField(
            model_name='programtopic',
            name='hours',
            field=models.DecimalField(decimal_places=1, help_text='Количество часов, выделенное на эту тему в данной программе', max_digits=4, verbose_name='Часов на тему'),
        ),
        migrations.AlterField(
            model_name='programtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_assignments', to='reference.lessontopic'),
        ),
        migrations.AlterField(
            model_name='subjectset',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='sets', to='reference.subjectdictionary', verbose_name='Предметы'),
        ),
        migrations.AlterUniqueTogether(
            name='lessontopic',
            unique_together={('subject', 'topic_number', 'is_pz')},
        ),
    ]
