# Generated by Django 6.0.4 on 2026-07-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0016_alter_groupcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'ordering': ['code'], 'verbose_name': 'Категория', 'verbose_name_plural': ' Категории'},
        ),
        migrations.AlterModelOptions(
            name='lessontopic',
            options={'ordering': ['subject', 'topic_number', 'is_pz'], 'verbose_name': 'Тема занятия', 'verbose_name_plural': '📚 Темы занятий'},
        ),
        migrations.AlterModelOptions(
            name='programtopic',
            options={'ordering': ['topic__topic_number']},
        ),
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'ordering': ['name'], 'verbose_name': 'Программа обучения', 'verbose_name_plural': '📋 Программы обучения'},
        ),
        migrations.AlterField(
            model_name='lessontopic',
            name='hours',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='programsubject',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Включён'),
        ),
        migrations.AlterField(
            model_name='programsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='reference.subjectdictionary'),
        ),
        migrations.AlterField(
            model_name='programtopic',
            name='hours',
            field=models.DecimalField(decimal_places=1, help_text='Количество часов на эту тему', max_digits=4, verbose_name='Часов'),
        ),
        migrations.AlterField(
            model_name='programtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_topics', to='reference.lessontopic'),
        ),
        migrations.AlterField(
            model_name='subjectset',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subject_sets', to='reference.subjectdictionary', verbose_name='Предметы'),
        ),
    ]
