# Generated by Django 6.0.4 on 2026-07-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_alter_groupcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontopic',
            options={'verbose_name': 'Тема занятия', 'verbose_name_plural': '📚 Темы занятий'},
        ),
        migrations.AlterUniqueTogether(
            name='lessontopic',
            unique_together=set(),
        ),
    ]
