# Generated by Django 6.0.4 on 2026-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0018_alter_lessontopic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogram',
            name='plan_graphic_title',
            field=models.CharField(blank=True, default='План-график выполнения единой программы', help_text='Текст заголовка, который будет подставлен в Excel-файл план-графика', max_length=300, verbose_name='План-график выполнения единой программы'),
        ),
    ]
