# Generated by Django 6.0.4 on 2026-09-14 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(help_text='Формат: +375 (29) 123-45-67', max_length=25, validators=[django.core.validators.RegexValidator(message='Формат: +375 (29) 123-45-67', regex='^\\+375\\s?\\(\\d{2}\\)\\s?\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон')),
                ('contract_main', models.BooleanField(default=False, verbose_name='По основному договору')),
                ('contract_part_time', models.BooleanField(default=False, verbose_name='По договору совмещения')),
                ('teaches_truck', models.BooleanField(default=False, verbose_name='🚛 Грузовой')),
                ('teaches_car', models.BooleanField(default=False, verbose_name='🚗 Легковой')),
                ('schedule_morning', models.BooleanField(default=False, verbose_name='🌅 Утро')),
                ('schedule_evening', models.BooleanField(default=False, verbose_name='🌆 Вечер')),
                ('schedule_weekend', models.BooleanField(default=False, verbose_name='📅 Выходной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': '📚 Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
