# Generated by Django 6.0.4 on 2026-05-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_classroom_options_and_more'),
        ('teachers', '0002_teacher_classroom_delete_teacheraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Выберите аудиторию из справочника', limit_choices_to={'contract_end__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classrooms.classroom', verbose_name='Место проведения занятий'),
        ),
    ]
