# Generated by Django 6.0.4 on 2026-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_teacher_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contract_main',
            field=models.BooleanField(default=False, help_text='✅ Отметьте, если преподаватель работает по основному договору', verbose_name='По основному договору'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='contract_part_time',
            field=models.BooleanField(default=False, help_text='✅ Отметьте, если преподаватель работает по совместительству', verbose_name='По договору совмещения'),
        ),
    ]
