# Generated by Django 6.0.4 on 2026-05-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_contract_main_teacher_contract_part_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contract_main',
            field=models.BooleanField(default=False, verbose_name='По основному договору'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contract_part_time',
            field=models.BooleanField(default=False, verbose_name='По договору совмещения'),
        ),
    ]
