# Generated by Django 6.0.4 on 2026-05-05 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название/Сервис')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Логин/Пользователь')),
                ('encrypted_password', models.TextField(verbose_name='Зашифрованный пароль')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка (опц.)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Доступно ролям')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Запись в хранилище',
                'verbose_name_plural': 'Хранилище паролей',
            },
        ),
    ]
