# Generated by Django 6.0.4 on 2026-09-14 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(default='', max_length=100, verbose_name='Должность')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Логин/Пользователь')),
                ('encrypted_password', models.TextField(verbose_name='Зашифрованный пароль')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка (опц.)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, to='auth.group', verbose_name='Доступно ролям')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Запись в хранилище',
                'verbose_name_plural': 'Хранилище паролей',
            },
        ),
        migrations.CreateModel(
            name='VaultPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_groups', models.BooleanField(default=False, verbose_name='👥 Группы (раздел)')),
                ('can_view_students', models.BooleanField(default=False, verbose_name='🎓 Учащиеся (раздел)')),
                ('can_view_credits', models.BooleanField(default=False, verbose_name='✅ Зачёты (раздел)')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='📊 Отчёты (раздел)')),
                ('can_view_references', models.BooleanField(default=False, verbose_name='📁 Справочники (раздел)')),
                ('perm_grp_create', models.BooleanField(default=False, verbose_name='Создание группы')),
                ('perm_grp_list', models.BooleanField(default=False, verbose_name='Список групп')),
                ('perm_grp_schedule1', models.BooleanField(default=False, verbose_name='План-графики 1')),
                ('perm_grp_schedule2', models.BooleanField(default=False, verbose_name='План-графики 2')),
                ('perm_grp_timetable', models.BooleanField(default=False, verbose_name='Расписание')),
                ('perm_grp_close', models.BooleanField(default=False, verbose_name='Закрытие групп')),
                ('perm_stu_list', models.BooleanField(default=False, verbose_name='Список учащихся')),
                ('perm_stu_create', models.BooleanField(default=False, verbose_name='Создание учащегося')),
                ('perm_stu_progress', models.BooleanField(default=False, verbose_name='Прогресс обучения')),
                ('perm_stu_dismiss', models.BooleanField(default=False, verbose_name='Отчисления')),
                ('perm_cred_dashboard', models.BooleanField(default=False, verbose_name='Панель зачётов')),
                ('perm_cred_add', models.BooleanField(default=False, verbose_name='Добавление зачёта')),
                ('perm_cred_reports', models.BooleanField(default=False, verbose_name='Отчёты по экзаменам')),
                ('perm_rep_dashboard', models.BooleanField(default=False, verbose_name='Панель отчётов')),
                ('perm_rep_generate', models.BooleanField(default=False, verbose_name='Генерация отчётов')),
                ('perm_rep_export', models.BooleanField(default=False, verbose_name='Экспорт данных')),
                ('perm_ref_classrooms', models.BooleanField(default=False, verbose_name='Аудитории')),
                ('perm_ref_teachers', models.BooleanField(default=False, verbose_name='Преподаватели')),
                ('perm_ref_masters', models.BooleanField(default=False, verbose_name='Мастера')),
                ('perm_ref_topics', models.BooleanField(default=False, verbose_name='Темы занятий')),
                ('perm_ref_categories', models.BooleanField(default=False, verbose_name='Категории')),
                ('perm_vault_list', models.BooleanField(default=False, verbose_name='Список записей')),
                ('perm_vault_add', models.BooleanField(default=False, verbose_name='Добавление записи')),
                ('perm_vault_manage', models.BooleanField(default=False, verbose_name='Управление доступом')),
                ('perm_admin_access', models.BooleanField(default=False, verbose_name='Доступ к админке')),
                ('can_view_vault', models.BooleanField(default=False, verbose_name='🔐 Хранилище')),
                ('can_view_admin', models.BooleanField(default=False, verbose_name='⚙️ Админка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vault_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='vault.vaultentry', verbose_name='Запись хранилища')),
            ],
            options={
                'verbose_name': 'Разрешение доступа',
                'verbose_name_plural': 'Разрешения доступа',
                'ordering': ['user__username', 'vault_entry__full_name'],
                'unique_together': {('user', 'vault_entry')},
            },
        ),
    ]
