# Generated by Django 6.0.4 on 2026-05-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultentry',
            name='title',
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='full_name',
            field=models.CharField(default='', max_length=200, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='vaultentry',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Должность'),
        ),
    ]
