# Generated by Django 6.0.4 on 2026-06-16 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_remove_vaultentry_title_vaultentry_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_main', models.BooleanField(default=False, verbose_name='🏠 Главная')),
                ('can_view_groups', models.BooleanField(default=False, verbose_name='👥 Группы')),
                ('can_view_students', models.BooleanField(default=False, verbose_name='🎓 Учащиеся')),
                ('can_view_credits', models.BooleanField(default=False, verbose_name='✅ Зачёты и экзамены')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='📊 Отчёты')),
                ('can_view_references', models.BooleanField(default=False, verbose_name='📁 Справочники (все)')),
                ('can_view_classrooms', models.BooleanField(default=False, verbose_name='  └ Аудитории')),
                ('can_view_teachers', models.BooleanField(default=False, verbose_name='  └ Преподаватели')),
                ('can_view_masters', models.BooleanField(default=False, verbose_name='  └ Мастера')),
                ('can_view_cars', models.BooleanField(default=False, verbose_name='  └ Автопарк')),
                ('can_view_topics', models.BooleanField(default=False, verbose_name='  └ Темы занятий')),
                ('can_view_categories', models.BooleanField(default=False, verbose_name='  └ Категории')),
                ('can_view_vault', models.BooleanField(default=False, verbose_name='🔐 Хранилище')),
                ('can_view_admin', models.BooleanField(default=False, verbose_name='⚙️ Админка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vault_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='vault.vaultentry', verbose_name='Запись хранилища')),
            ],
            options={
                'verbose_name': 'Разрешение доступа',
                'verbose_name_plural': 'Разрешения доступа',
                'ordering': ['user__username', 'vault_entry__full_name'],
                'unique_together': {('user', 'vault_entry')},
            },
        ),
    ]
