# Generated by Django 6.0.4 on 2026-06-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_vaultpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultpermission',
            name='can_view_groups_add',
            field=models.BooleanField(default=False, verbose_name='  └ Добавление'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='can_view_groups_delete',
            field=models.BooleanField(default=False, verbose_name='  └ Удаление'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='can_view_groups_edit',
            field=models.BooleanField(default=False, verbose_name='  └ Редактирование'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='can_view_groups_list',
            field=models.BooleanField(default=False, verbose_name='  └ Просмотр списка'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='can_view_groups_schedule',
            field=models.BooleanField(default=False, verbose_name='  └ План-графики'),
        ),
    ]
