# Generated by Django 6.0.4 on 2026-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_vaultpermission_can_view_groups_add_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_cars',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_categories',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_classrooms',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_groups_add',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_groups_delete',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_groups_edit',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_groups_list',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_groups_schedule',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_masters',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_references',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_teachers',
        ),
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_topics',
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_admin_access',
            field=models.BooleanField(default=False, verbose_name='Доступ к админке'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_cred_add',
            field=models.BooleanField(default=False, verbose_name='Добавление зачёта'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_cred_dashboard',
            field=models.BooleanField(default=False, verbose_name='Панель зачётов'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_cred_reports',
            field=models.BooleanField(default=False, verbose_name='Отчёты по экзаменам'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_grp_close',
            field=models.BooleanField(default=False, verbose_name='Закрытие групп'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_grp_create',
            field=models.BooleanField(default=False, verbose_name='Создание группы'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_grp_list',
            field=models.BooleanField(default=False, verbose_name='Список групп'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_grp_schedule1',
            field=models.BooleanField(default=False, verbose_name='План-графики 1'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_grp_schedule2',
            field=models.BooleanField(default=False, verbose_name='План-графики 2'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_grp_timetable',
            field=models.BooleanField(default=False, verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_ref_categories',
            field=models.BooleanField(default=False, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_ref_classrooms',
            field=models.BooleanField(default=False, verbose_name='Аудитории'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_ref_masters',
            field=models.BooleanField(default=False, verbose_name='Мастера'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_ref_teachers',
            field=models.BooleanField(default=False, verbose_name='Преподаватели'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_ref_topics',
            field=models.BooleanField(default=False, verbose_name='Темы занятий'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_rep_dashboard',
            field=models.BooleanField(default=False, verbose_name='Панель отчётов'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_rep_export',
            field=models.BooleanField(default=False, verbose_name='Экспорт данных'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_rep_generate',
            field=models.BooleanField(default=False, verbose_name='Генерация отчётов'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_stu_create',
            field=models.BooleanField(default=False, verbose_name='Создание учащегося'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_stu_dismiss',
            field=models.BooleanField(default=False, verbose_name='Отчисления'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_stu_list',
            field=models.BooleanField(default=False, verbose_name='Список учащихся'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_stu_progress',
            field=models.BooleanField(default=False, verbose_name='Прогресс обучения'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_vault_add',
            field=models.BooleanField(default=False, verbose_name='Добавление записи'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_vault_list',
            field=models.BooleanField(default=False, verbose_name='Список записей'),
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='perm_vault_manage',
            field=models.BooleanField(default=False, verbose_name='Управление доступом'),
        ),
    ]
