# Generated by Django 6.0.4 on 2026-06-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_remove_vaultpermission_can_view_cars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultpermission',
            name='can_view_main',
        ),
        migrations.AddField(
            model_name='vaultpermission',
            name='can_view_references',
            field=models.BooleanField(default=False, verbose_name='📁 Справочники (раздел)'),
        ),
        migrations.AlterField(
            model_name='vaultpermission',
            name='can_view_credits',
            field=models.BooleanField(default=False, verbose_name='✅ Зачёты (раздел)'),
        ),
        migrations.AlterField(
            model_name='vaultpermission',
            name='can_view_groups',
            field=models.BooleanField(default=False, verbose_name='👥 Группы (раздел)'),
        ),
        migrations.AlterField(
            model_name='vaultpermission',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='📊 Отчёты (раздел)'),
        ),
        migrations.AlterField(
            model_name='vaultpermission',
            name='can_view_students',
            field=models.BooleanField(default=False, verbose_name='🎓 Учащиеся (раздел)'),
        ),
    ]
