# Generated by Django 6.0.4 on 2026-05-05 09:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{6}$', 'Ровно 6 заглавных букв или цифр')], verbose_name='№ группы')),
                ('category', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Ровно 2 заглавные буквы')], verbose_name='Категория')),
                ('classroom', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{4}$', 'Ровно 4 символа')], verbose_name='Аудитория')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Действие договора с')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='по')),
                ('status', models.CharField(choices=[('active', '🟢 Активная'), ('archived', '⚪ Архив')], default='active', max_length=10, verbose_name='Статус')),
                ('schedule_type', models.CharField(choices=[('odd', '📅 Нечётные дни (пн-пт)'), ('even', '📅 Чётные дни (пн-пт)'), ('weekend', '📅 Выходные (сб-вс)')], max_length=10, verbose_name='Тип расписания')),
                ('schedule_exceptions', models.JSONField(blank=True, default=list, help_text='Даты в формате ГГГГ-ММ-ДД через запятую', verbose_name='Исключения из расписания')),
                ('time_session', models.CharField(choices=[('morning', '🌅 Утренняя'), ('evening', '🌆 Вечерняя')], max_length=10, verbose_name='Смена')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Начало')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Окончание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'teachers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': '👥 Группы',
                'ordering': ['-created_at'],
            },
        ),
    ]
