# Generated by Django 6.0.4 on 2026-09-14 12:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('theory', ' Теория'), ('driving', '🚗 Вождение')], max_length=10, verbose_name='Тип экзамена')),
                ('attempt_type', models.CharField(choices=[('free', 'Бесплатная'), ('paid', 'Платная')], max_length=10, verbose_name='Тип попытки')),
                ('status', models.CharField(choices=[('passed', '✅ Сдал'), ('failed', '❌ Не сдал')], max_length=10, verbose_name='Статус')),
                ('exam_date', models.DateField(verbose_name='Дата экзамена')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Результат экзамена',
                'verbose_name_plural': '🎓 Результаты экзаменов',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,6}$', 'Введите от 1 до 6 заглавных букв или цифр')], verbose_name='№ группы')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='Начало договора')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='Окончание договора')),
                ('exam_internal_theory_date', models.DateField(blank=True, null=True, verbose_name='📚 Внутренний экзамен: ПДД')),
                ('exam_internal_driving_date', models.DateField(blank=True, null=True, verbose_name='🚗 Внутренний экзамен: Вождение')),
                ('exam_gai_date', models.DateField(blank=True, null=True, verbose_name='🏁 Экзамен в ГАИ')),
                ('status', models.CharField(choices=[('active', '🟢 Активна'), ('paused', '🟡 Приостановлена'), ('closed', ' Закрыта')], default='active', max_length=20, verbose_name='Статус')),
                ('schedule_type', models.CharField(blank=True, choices=[('odd', '📅 Нечётные дни (пн-пт)'), ('even', '📅 Чётные дни (пн-пт)'), ('weekend', '📅 Выходные (сб-вс)'), ('directed', '📅 По указанию')], default='directed', max_length=15, verbose_name='Тип расписания')),
                ('duration', models.CharField(blank=True, choices=[('standard', 'Стандартный'), ('accelerated', 'Ускоренный')], default='standard', max_length=15, null=True, verbose_name='Срок обучения')),
                ('schedule_exceptions', models.JSONField(blank=True, default=list, verbose_name='Исключения из расписания')),
                ('comments', models.TextField(blank=True, help_text='Внутренние заметки по группе', verbose_name='Комментарии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('change_log', models.TextField(blank=True, editable=False, verbose_name='Журнал изменений')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': '👥 Группы',
                'ordering': ['group_number'],
            },
        ),
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_dates', models.JSONField(blank=True, default=list, verbose_name='Исключенные даты (кроме)')),
                ('additional_dates', models.JSONField(blank=True, default=list, verbose_name='Дополнительные даты')),
                ('title', models.CharField(editable=False, max_length=255, verbose_name='Заголовок')),
                ('date_start', models.DateField(verbose_name='Начало периода')),
                ('date_end', models.DateField(verbose_name='Конец периода')),
                ('required_hours', models.PositiveIntegerField(default=170, verbose_name='Количество часов')),
                ('schedule_type', models.CharField(choices=[('even', 'Чётные дни'), ('odd', 'Нечётные дни'), ('weekend', 'Выходные дни'), ('custom', 'По указанию')], default='custom', max_length=20, verbose_name='Тип расписания')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('class_days', models.JSONField(blank=True, default=dict, verbose_name='Дни занятий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'План-график',
                'verbose_name_plural': 'План-графики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_date', models.DateField(verbose_name='Дата зачёта')),
                ('status', models.CharField(choices=[('passed', '✅ Сдал'), ('failed', ' Не сдал')], default='failed', max_length=10, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('chairman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_credits', to='teachers.teacher', verbose_name='Председатель комиссии')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reference.credit', verbose_name='Зачёт')),
                ('member1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member1_credits', to='teachers.teacher', verbose_name='Член комиссии 1')),
                ('member2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2_credits', to='teachers.teacher', verbose_name='Член комиссии 2')),
                ('member3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member3_credits', to='teachers.teacher', verbose_name='Член комиссии 3')),
            ],
            options={
                'verbose_name': 'Результат зачёта',
                'verbose_name_plural': '📋 Результаты зачётов',
                'ordering': ['-credit_date'],
            },
        ),
    ]
