# Generated by Django 6.0.4 on 2026-05-06 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0001_initial'),
        ('groups', '0002_alter_group_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='classrooms.classroom', verbose_name='Аудитория'),
        ),
    ]
