# Generated by Django 6.0.4 on 2026-05-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_classroom'),
        ('reference', '0003_alter_groupcategory_options_alter_groupcategory_hint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-start_date'], 'verbose_name': 'Группа', 'verbose_name_plural': '👥 Группы'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='group',
            name='contract_end',
        ),
        migrations.RemoveField(
            model_name='group',
            name='contract_start',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_exceptions',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_type',
        ),
        migrations.RemoveField(
            model_name='group',
            name='status',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='group',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='group',
            name='time_session',
        ),
        migrations.RemoveField(
            model_name='group',
            name='time_start',
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Доп. информация о группе', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='group',
            name='duration',
            field=models.CharField(choices=[('standard', '📘 Стандартный'), ('accelerated', '🚀 Ускоренный')], default='standard', help_text='Стандартный: ~4-5 месяцев, Ускоренный: ~2-3 месяца', max_length=20, verbose_name='Срок обучения'),
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_fri',
            field=models.BooleanField(default=False, verbose_name='Пт'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_mon',
            field=models.BooleanField(default=False, verbose_name='Пн'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_sat',
            field=models.BooleanField(default=False, verbose_name='Сб'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_thu',
            field=models.BooleanField(default=False, verbose_name='Чт'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_time',
            field=models.CharField(blank=True, help_text='Например: 18:00-20:00', max_length=50, verbose_name='Время занятий'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_tue',
            field=models.BooleanField(default=False, verbose_name='Вт'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_wed',
            field=models.BooleanField(default=False, verbose_name='Ср'),
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='reference.groupcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.CharField(help_text='Например: АВ-2026-01', max_length=50, unique=True, verbose_name='№ группы'),
        ),
    ]
