# Generated by Django 6.0.4 on 2026-05-15 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0002_alter_classroom_options_and_more'),
        ('groups', '0004_alter_group_options_remove_group_classroom_and_more'),
        ('reference', '0003_alter_groupcategory_options_alter_groupcategory_hint'),
        ('teachers', '0004_remove_teacher_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group_number'], 'verbose_name': 'Группа', 'verbose_name_plural': '👥 Группы'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_fri',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_mon',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_sat',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_thu',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_tue',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_wed',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
        migrations.AddField(
            model_name='group',
            name='change_log',
            field=models.TextField(blank=True, editable=False, help_text='Автоматически ведётся при каждом сохранении', verbose_name='Журнал изменений'),
        ),
        migrations.AddField(
            model_name='group',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='classrooms.classroom', verbose_name='Аудитория'),
        ),
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True, help_text='Внутренние заметки по группе', verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='group',
            name='contract_end',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание договора'),
        ),
        migrations.AddField(
            model_name='group',
            name='contract_start',
            field=models.DateField(blank=True, null=True, verbose_name='Начало договора'),
        ),
        migrations.AddField(
            model_name='group',
            name='daily_schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='Расписание занятий группы'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_exceptions',
            field=models.JSONField(blank=True, default=list, help_text='Даты в формате ДД-ММ-ГГГГ через запятую', verbose_name='Исключения из расписания'),
        ),
        migrations.AddField(
            model_name='group',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('odd', '📅 Нечётные дни (пн-пт)'), ('even', '📅 Чётные дни (пн-пт)'), ('weekend', '📅 Выходные (сб-вс)'), ('directed', '📅 По указанию')], default='directed', max_length=15, verbose_name='Тип расписания'),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', '🟢 Активна'), ('paused', '🟡 Приостановлена'), ('closed', '🔒 Закрыта')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_session',
            field=models.CharField(blank=True, choices=[('morning', '🌅 Утренняя'), ('evening', '🌆 Вечерняя')], max_length=10, null=True, verbose_name='Смена'),
        ),
        migrations.AddField(
            model_name='group',
            name='time_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='group',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.groupcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='group',
            name='duration',
            field=models.CharField(blank=True, choices=[('standard', 'Стандартный'), ('accelerated', 'Ускоренный')], max_length=15, null=True, verbose_name='Срок обучения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,6}$', 'Введите от 1 до 6 заглавных букв или цифр')], verbose_name='№ группы'),
        ),
    ]
