# Generated by Django 6.0.4 on 2026-05-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_options_remove_group_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='daily_schedule',
        ),
    ]
