# Generated by Django 6.0.4 on 2026-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_remove_group_daily_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='duration',
            field=models.CharField(blank=True, choices=[('standard', 'Стандартный'), ('accelerated', 'Ускоренный')], default='standard', max_length=15, null=True, verbose_name='Срок обучения'),
        ),
    ]
