# Generated by Django 6.0.4 on 2026-05-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_group_duration'),
        ('students', '0016_alter_studenthistory_options'),
        ('teachers', '0004_remove_teacher_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Зачёт',
                'verbose_name_plural': '✅ Зачёты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('theory', '📚 Теория'), ('driving', '🚗 Вождение')], max_length=10, verbose_name='Тип экзамена')),
                ('attempt_type', models.CharField(choices=[('free', 'Бесплатная'), ('paid', 'Платная')], max_length=10, verbose_name='Тип попытки')),
                ('status', models.CharField(choices=[('passed', '✅ Сдал'), ('failed', '❌ Не сдал')], max_length=10, verbose_name='Статус')),
                ('exam_date', models.DateField(verbose_name='Дата экзамена')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Экзаменатор')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student', verbose_name='Учащийся')),
            ],
            options={
                'verbose_name': 'Результат экзамена',
                'verbose_name_plural': '🎓 Результаты экзаменов',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_date', models.DateField(verbose_name='Дата зачёта')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='groups.credit', verbose_name='Зачёт')),
                ('examiner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Экзаменатор')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_results', to='students.student', verbose_name='Учащийся')),
            ],
            options={
                'verbose_name': 'Результат зачёта',
                'verbose_name_plural': '📋 Результаты зачётов',
                'ordering': ['-credit_date'],
                'unique_together': {('student', 'credit')},
            },
        ),
    ]
