# Generated by Django 6.0.4 on 2026-05-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_credit_examresult_creditresult'),
        ('reference', '0005_alter_credit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditresult',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reference.credit', verbose_name='Зачёт'),
        ),
    ]
