# Generated by Django 6.0.4 on 2026-05-22 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_creditresult_credit'),
        ('teachers', '0004_remove_teacher_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credit',
        ),
        migrations.RemoveField(
            model_name='creditresult',
            name='examiner',
        ),
        migrations.AddField(
            model_name='creditresult',
            name='chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_credits', to='teachers.teacher', verbose_name='Председатель комиссии'),
        ),
        migrations.AddField(
            model_name='creditresult',
            name='member1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member1_credits', to='teachers.teacher', verbose_name='Член комиссии 1'),
        ),
        migrations.AddField(
            model_name='creditresult',
            name='member2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2_credits', to='teachers.teacher', verbose_name='Член комиссии 2'),
        ),
        migrations.AddField(
            model_name='creditresult',
            name='member3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member3_credits', to='teachers.teacher', verbose_name='Член комиссии 3'),
        ),
        migrations.AlterField(
            model_name='group',
            name='change_log',
            field=models.TextField(blank=True, editable=False, verbose_name='Журнал изменений'),
        ),
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='group',
            name='schedule_exceptions',
            field=models.JSONField(blank=True, default=list, verbose_name='Исключения из расписания'),
        ),
    ]
