# Generated by Django 6.0.4 on 2026-05-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_delete_credit_remove_creditresult_examiner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditresult',
            unique_together=set(),
        ),
    ]
