# Generated by Django 6.0.4 on 2026-05-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_alter_creditresult_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditresult',
            name='status',
            field=models.CharField(choices=[('passed', '✅ Сдал'), ('failed', '❌ Не сдал')], default='failed', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True, help_text='Внутренние заметки по группе', verbose_name='Комментарии'),
        ),
    ]
