# Generated by Django 6.0.4 on 2026-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_creditresult_status_alter_group_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='exam_gai_date',
            field=models.DateField(blank=True, null=True, verbose_name='🏁 Экзамен в ГАИ'),
        ),
        migrations.AddField(
            model_name='group',
            name='exam_internal_driving_date',
            field=models.DateField(blank=True, null=True, verbose_name='🚗 Внутренний экзамен: Вождение'),
        ),
        migrations.AddField(
            model_name='group',
            name='exam_internal_theory_date',
            field=models.DateField(blank=True, null=True, verbose_name='📚 Внутренний экзамен: ПДД'),
        ),
    ]
