# Generated by Django 6.0.4 on 2026-05-27 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_group_exam_gai_date_group_exam_internal_driving_date_and_more'),
        ('teachers', '0006_alter_teacher_contract_main_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=255, verbose_name='Заголовок')),
                ('date_start', models.DateField(verbose_name='Начало периода')),
                ('date_end', models.DateField(verbose_name='Конец периода')),
                ('time_start', models.TimeField(default='09:00', verbose_name='Время начала')),
                ('time_end', models.TimeField(default='12:00', verbose_name='Время окончания')),
                ('schedule_type', models.CharField(choices=[('even', 'Чётные дни'), ('odd', 'Нечётные дни'), ('weekend', 'Выходные дни'), ('custom', 'По указанию')], default='custom', max_length=20, verbose_name='Тип расписания')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Место проведения')),
                ('class_days', models.JSONField(blank=True, default=dict, verbose_name='Дни занятий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(limit_choices_to={'status': 'active'}, on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Учебная группа')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'План-график 1 (о)',
                'verbose_name_plural': 'План-графики 1 (о)',
                'ordering': ['-created_at'],
            },
        ),
    ]
