# Generated by Django 6.0.4 on 2026-05-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_scheduleplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleplan',
            name='required_hours',
            field=models.PositiveIntegerField(default=170, verbose_name='Количество часов'),
        ),
    ]
