# Generated by Django 6.0.4 on 2026-05-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_scheduleplan_required_hours'),
        ('teachers', '0006_alter_teacher_contract_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'План-график', 'verbose_name_plural': 'План-графики'},
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='med_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_schedule_plans', to='teachers.teacher', verbose_name='Преподаватель медицины'),
        ),
        migrations.AlterField(
            model_name='creditresult',
            name='status',
            field=models.CharField(choices=[('passed', '✅ Сдал'), ('failed', ' Не сдал')], default='failed', max_length=10, verbose_name='Статус'),
        ),
    ]
