# Generated by Django 6.0.4 on 2026-06-04 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_alter_scheduleplan_options_scheduleplan_med_teacher_and_more'),
        ('teachers', '0006_alter_teacher_contract_main_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='group',
            name='time_session',
        ),
        migrations.RemoveField(
            model_name='group',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='scheduleplan',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='scheduleplan',
            name='time_start',
        ),
        migrations.AlterField(
            model_name='examresult',
            name='exam_type',
            field=models.CharField(choices=[('theory', ' Теория'), ('driving', '🚗 Вождение')], max_length=10, verbose_name='Тип экзамена'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', '🟢 Активна'), ('paused', '🟡 Приостановлена'), ('closed', ' Закрыта')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddConstraint(
            model_name='scheduleplan',
            constraint=models.UniqueConstraint(fields=('group', 'date_start', 'date_end'), name='unique_group_schedule_period'),
        ),
    ]
