# Generated by Django 6.0.4 on 2026-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_remove_group_time_end_remove_group_time_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleplan',
            name='additional_dates',
            field=models.JSONField(blank=True, default=list, verbose_name='Дополнительные даты'),
        ),
        migrations.AddField(
            model_name='scheduleplan',
            name='excluded_dates',
            field=models.JSONField(blank=True, default=list, verbose_name='Исключенные даты (кроме)'),
        ),
    ]
