# Generated by Django 6.0.4 on 2026-07-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_scheduleplan_additional_dates_and_more'),
        ('reference', '0018_alter_lessontopic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleplan',
            name='training_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.trainingprogram', verbose_name='Учебная программа'),
        ),
    ]
